const MODES={TRANSLATION:'translation',CLOZE_CHOICE:'cloze-choice',CLOZE_INPUT:'cloze-input'};
const FINNISH_LETTERS=[...'abcdefghijklmnopqrstuvwxyzåäö'];
const state={words:[],wordMap:new Map(),current:null,currentExample:null,focusedRank:null,answered:false,mode:localStorage.getItem('fiQuizMode')||MODES.TRANSLATION,view:'home',detailWord:null,revealedHintPositions:new Set(),correct:Number(localStorage.getItem('fiQuizCorrect')||0),total:Number(localStorage.getItem('fiQuizTotal')||0)};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const els={home:$('#home-view'),dictionary:$('#dictionary-view'),mobileTitle:$('#mobile-view-title'),viewLinks:$$('[data-view-link]'),loading:$('#loading'),error:$('#error'),content:$('#quiz-content'),questionLabel:$('#quiz-title'),wordRow:$('#word-row'),word:$('#word'),rank:$('#rank'),sentencePanel:$('#sentence-panel'),clozeSentence:$('#cloze-sentence'),clozeTranslation:$('#cloze-translation'),options:$('#options'),typingForm:$('#typing-form'),typedAnswer:$('#typed-answer'),letterKeyboard:$('#letter-keyboard'),keyboardBackspace:$('#keyboard-backspace'),keyboardClear:$('#keyboard-clear'),hintButtons:$$('.hint-button'),hintPattern:$('#hint-pattern'),modeButtons:$$('.mode-button'),feedback:$('#feedback'),feedbackBackdrop:$('#feedback-backdrop'),feedbackStatusIcon:$('#feedback-status-icon'),answerEffect:$('#answer-effect'),result:$('#result-message'),exampleFi:$('#example-fi'),exampleFa:$('#example-fa'),next:$('#next-word'),correctCount:$('#correct-count'),totalCount:$('#total-count'),reset:$('#reset-score'),speak:$('#speak-word'),dictionaryListPanel:$('#dictionary-list-panel'),dictionaryDetail:$('#dictionary-detail'),dictionarySearch:$('#dictionary-search'),dictionarySort:$('#dictionary-sort'),dictionaryPosFilter:$('#dictionary-pos-filter'),dictionaryList:$('#dictionary-list'),dictionaryEmpty:$('#dictionary-empty'),dictionaryCount:$('#dictionary-count'),dictionaryBack:$('#dictionary-back'),detailWord:$('#detail-word'),detailTranslation:$('#detail-translation'),detailRank:$('#detail-rank'),detailPos:$('#detail-pos'),detailLemma:$('#detail-lemma'),detailExamples:$('#detail-examples'),detailSpeak:$('#detail-speak'),practiceButtons:$$('[data-practice-mode]')};
const faNumber=n=>new Intl.NumberFormat('fa-IR').format(n);const normalize=v=>v.trim().normalize('NFC').toLocaleLowerCase('fi-FI');const wordLength=w=>[...w].length;
function updateScore(){els.correctCount.textContent=faNumber(state.correct);els.totalCount.textContent=faNumber(state.total);localStorage.setItem('fiQuizCorrect',state.correct);localStorage.setItem('fiQuizTotal',state.total)}
function shuffle(a){const c=[...a];for(let i=c.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[c[i],c[j]]=[c[j],c[i]]}return c}
function getExamples(w){return[{fi:w.example_fi,fa:w.example_fa},{fi:w.example_2_fi,fa:w.example_2_fa}].filter(x=>x.fi&&x.fa)}
function randomExample(w){const a=getExamples(w);return a[Math.floor(Math.random()*a.length)]}
function getRandomWord(except=null){if(state.focusedRank){const w=state.words.find(x=>x.rank===state.focusedRank);state.focusedRank=null;if(w)return w}const p=state.words.filter(x=>x.rank!==except);return p[Math.floor(Math.random()*p.length)]}
function makeTranslationOptions(w){return shuffle([w,...shuffle(state.words.filter(x=>x.rank!==w.rank)).slice(0,3)])}
function makeFinnishOptions(w){const len=wordLength(w.word);const c=shuffle(state.words.filter(x=>x.rank!==w.rank)).sort((a,b)=>Math.abs(wordLength(a.word)-len)-Math.abs(wordLength(b.word)-len));return shuffle([w,...c.slice(0,3)])}
function escapeRegExp(v){return v.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}
function makeBlank(w){return '＿'.repeat(Math.max(3,wordLength(w)))}
function updateModeButtons(){els.modeButtons.forEach(b=>{const on=b.dataset.mode===state.mode;b.classList.toggle('active',on);b.setAttribute('aria-selected',on)})}
function resetHints(){state.revealedHintPositions=new Set();els.hintPattern.hidden=true;els.hintPattern.textContent='';els.hintButtons.forEach((b,i)=>{b.disabled=i!==0;b.classList.remove('used')})}
function revealHint(i){if(state.answered||state.mode!==MODES.CLOZE_INPUT)return;const letters=[...state.current.word];const pos=i===0?0:i===1?letters.length-1:Math.min(1,letters.length-1);state.revealedHintPositions.add(pos);els.hintPattern.textContent=letters.map((l,n)=>state.revealedHintPositions.has(n)?l:'ـ').join(' ');els.hintPattern.hidden=false;els.hintButtons[i].disabled=true;els.hintButtons[i].classList.add('used');if(els.hintButtons[i+1])els.hintButtons[i+1].disabled=false}
function optionSize(t){const n=[...t.trim()].length;return n<=10?'option-text-short':n<=22?'option-text-medium':n<=42?'option-text-long':'option-text-extra-long'}
function renderChoiceOptions(options,label,isFinnish=false){els.options.replaceChildren();els.options.hidden=false;options.forEach(w=>{const text=label(w),b=document.createElement('button');b.type='button';b.className=['option',isFinnish?'finnish-option':'',optionSize(text)].filter(Boolean).join(' ');b.textContent=text;b.dataset.rank=w.rank;b.addEventListener('click',()=>answerChoice(b,w));els.options.append(b)})}
function makeLetterKeyboard(word){const letters=[...new Set([...normalize(word)])];const count=Math.max(10,letters.length);const extras=shuffle(FINNISH_LETTERS.filter(l=>!letters.includes(l))).slice(0,count-letters.length);return shuffle([...letters,...extras])}
function setKeyboardDisabled(v){els.letterKeyboard.querySelectorAll('.letter-key').forEach(b=>b.disabled=v);els.keyboardBackspace.disabled=v;els.keyboardClear.disabled=v}
function moveCaretEnd(){const n=els.typedAnswer.value.length;els.typedAnswer.setSelectionRange(n,n)}
function insertLetter(l){if(state.answered||state.mode!==MODES.CLOZE_INPUT)return;els.typedAnswer.value+=l;moveCaretEnd()}
function removeLastLetter(){if(state.answered)return;const a=[...els.typedAnswer.value];a.pop();els.typedAnswer.value=a.join('');moveCaretEnd()}
function clearTyped(){if(state.answered)return;els.typedAnswer.value='';moveCaretEnd()}
function renderLetterKeyboard(word){els.letterKeyboard.replaceChildren();makeLetterKeyboard(word).forEach(l=>{const b=document.createElement('button');b.type='button';b.className='letter-key';b.textContent=l;b.addEventListener('click',()=>{insertLetter(l);b.classList.add('pressed');setTimeout(()=>b.classList.remove('pressed'),120)});els.letterKeyboard.append(b)});setKeyboardDisabled(false)}
function hideFeedback(){els.feedback.hidden=true;els.feedbackBackdrop.hidden=true;els.feedbackStatusIcon.className='feedback-status-icon'}
function playEffect(ok){const c=ok?'correct':'wrong';els.answerEffect.className=`answer-effect ${c}`;void els.answerEffect.offsetWidth;els.answerEffect.classList.add('show');setTimeout(()=>els.answerEffect.className='answer-effect',720)}
function makeWordLink(word,text=word.word){const b=document.createElement('button');b.type='button';b.className='dictionary-word-link';b.textContent=text;b.dataset.rank=word.rank;b.addEventListener('click',()=>openWordDetail(word));return b}
function renderLinkedSentence(container,sentence,blankWord=null){container.replaceChildren();const parts=sentence.split(/([\p{L}\p{N}]+)/gu);let blanked=false;parts.forEach(part=>{if(!part)return;const key=normalize(part);if(blankWord&&!blanked&&key===normalize(blankWord.word)){const span=document.createElement('span');span.className='cloze-blank';span.textContent=makeBlank(blankWord.word);container.append(span);blanked=true;return}const found=state.wordMap.get(key);container.append(found?makeWordLink(found,part):document.createTextNode(part))})}
function renderQuestion(){const prev=state.current?.rank??null;state.current=getRandomWord(prev);state.currentExample=randomExample(state.current);state.answered=false;hideFeedback();els.typingForm.hidden=true;els.options.hidden=true;els.options.replaceChildren();els.typedAnswer.blur();els.typedAnswer.value='';els.typedAnswer.disabled=false;els.typedAnswer.classList.remove('correct','wrong');els.letterKeyboard.replaceChildren();resetHints();updateModeButtons();if(state.mode===MODES.TRANSLATION){els.questionLabel.textContent='ترجمه این واژه چیست؟';els.wordRow.hidden=false;els.sentencePanel.hidden=true;els.word.textContent=state.current.word;els.rank.textContent=`#${state.current.rank}`;renderChoiceOptions(makeTranslationOptions(state.current),x=>x.translation_fa);return}els.wordRow.hidden=true;els.sentencePanel.hidden=false;renderLinkedSentence(els.clozeSentence,state.currentExample.fi,state.current);els.clozeTranslation.textContent=state.currentExample.fa;if(state.mode===MODES.CLOZE_CHOICE){els.questionLabel.textContent='کدام واژه جای خالی را کامل می‌کند؟';renderChoiceOptions(makeFinnishOptions(state.current),x=>x.word,true);return}els.questionLabel.textContent='واژه مناسب را در جای خالی بنویس.';els.typingForm.hidden=false;renderLetterKeyboard(state.current.word)}
function finishAnswer(ok){state.answered=true;state.total++;if(ok)state.correct++;const c=ok?'correct':'wrong';els.result.textContent=ok?'آفرین! پاسخ درست است.':state.mode===MODES.TRANSLATION?`پاسخ درست: ${state.current.translation_fa}`:`پاسخ درست: ${state.current.word} — ${state.current.translation_fa}`;els.result.className=`result-message ${c}`;els.feedbackStatusIcon.className=`feedback-status-icon ${c}`;renderLinkedSentence(els.exampleFi,state.currentExample.fi);els.exampleFa.textContent=state.currentExample.fa;els.feedbackBackdrop.hidden=false;els.feedback.hidden=false;updateScore();playEffect(ok)}
function answerChoice(button,w){if(state.answered)return;const ok=w.rank===state.current.rank;els.options.querySelectorAll('.option').forEach(b=>{b.disabled=true;if(Number(b.dataset.rank)===state.current.rank)b.classList.add('correct')});if(!ok)button.classList.add('wrong');finishAnswer(ok)}
function answerTyped(e){e.preventDefault();if(state.answered)return;const a=normalize(els.typedAnswer.value);if(!a)return;const ok=a===normalize(state.current.word);els.typedAnswer.blur();els.typedAnswer.disabled=true;els.typedAnswer.classList.add(ok?'correct':'wrong');els.hintButtons.forEach(b=>b.disabled=true);setKeyboardDisabled(true);finishAnswer(ok)}
function speak(word){if(!word||!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(word.word||word);u.lang='fi-FI';u.rate=.85;speechSynthesis.speak(u)}
function showView(view,{updateHash=true}={}){state.view=view;els.home.hidden=view!=='home';els.dictionary.hidden=view!=='dictionary';els.mobileTitle.textContent=view==='home'?'تمرین واژه‌ها':state.detailWord?`واژه: ${state.detailWord.word}`:'واژه‌نامه';els.viewLinks.forEach(a=>{const on=a.dataset.viewLink===view;a.classList.toggle('active',on);if(on)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});if(view==='dictionary'&&!state.detailWord)renderDictionaryList();if(updateHash)history.replaceState(null,'',view==='home'?'#home':'#dictionary')}
function populatePosFilter(){const map=new Map();state.words.forEach(w=>map.set(w.part_of_speech_fa||w.part_of_speech,w.part_of_speech_fa||w.part_of_speech));[...map.keys()].sort((a,b)=>a.localeCompare(b,'fa')).forEach(pos=>{const o=document.createElement('option');o.value=pos;o.textContent=pos;els.dictionaryPosFilter.append(o)})}
function filteredWords(){const q=normalize(els.dictionarySearch.value);const pos=els.dictionaryPosFilter.value;let list=state.words.filter(w=>{const hay=normalize([w.word,w.translation_fa,w.lemma,w.part_of_speech_fa,w.part_of_speech].join(' '));return(!q||hay.includes(q))&&(pos==='all'||(w.part_of_speech_fa||w.part_of_speech)===pos)});if(els.dictionarySort.value==='alphabetical')list.sort((a,b)=>a.word.localeCompare(b.word,'fi'));else list.sort((a,b)=>a.rank-b.rank);return list}
function renderDictionaryList(){state.detailWord=null;els.dictionaryDetail.hidden=true;els.dictionaryListPanel.hidden=false;els.mobileTitle.textContent='واژه‌نامه';const list=filteredWords();els.dictionaryList.replaceChildren();els.dictionaryCount.textContent=`${faNumber(list.length)} واژه`;els.dictionaryEmpty.hidden=list.length>0;list.forEach(w=>{const b=document.createElement('button');b.type='button';b.className='dictionary-list-item';b.innerHTML=`<span class="dictionary-rank">#${w.rank}</span><span class="dictionary-item-main"><strong class="dictionary-item-word" lang="fi">${w.word}</strong><span class="dictionary-item-translation">${w.translation_fa}</span></span><span class="dictionary-item-pos">${w.part_of_speech_fa||w.part_of_speech}</span>`;b.addEventListener('click',()=>openWordDetail(w));els.dictionaryList.append(b)})}
function openWordDetail(word){hideFeedback();state.detailWord=word;showView('dictionary');els.dictionaryListPanel.hidden=true;els.dictionaryDetail.hidden=false;els.mobileTitle.textContent=`واژه: ${word.word}`;els.detailWord.textContent=word.word;els.detailTranslation.textContent=word.translation_fa;els.detailRank.textContent=`#${word.rank}`;els.detailPos.textContent=word.part_of_speech_fa||word.part_of_speech;els.detailLemma.textContent=word.lemma;els.detailExamples.replaceChildren();getExamples(word).forEach(ex=>{const d=document.createElement('div');d.className='word-example-card';const p1=document.createElement('p');p1.className='word-example-fi';renderLinkedSentence(p1,ex.fi);const p2=document.createElement('p');p2.className='word-example-fa';p2.textContent=ex.fa;d.append(p1,p2);els.detailExamples.append(d)});history.replaceState(null,'',`#word-${word.rank}`);els.dictionaryDetail.scrollTop=0}
function startFocusedPractice(mode){if(!state.detailWord)return;state.mode=mode;state.focusedRank=state.detailWord.rank;localStorage.setItem('fiQuizMode',mode);showView('home');renderQuestion()}
function routeFromHash(){const h=location.hash;if(h.startsWith('#word-')&&state.words.length){const rank=Number(h.slice(6)),w=state.words.find(x=>x.rank===rank);if(w){openWordDetail(w);return}}showView(h==='#dictionary'?'dictionary':'home',{updateHash:false})}
async function init(){updateScore();try{const r=await fetch('./data/common-words.json?v=20260731-10');if(!r.ok)throw new Error(r.status);const d=await r.json();if(!Array.isArray(d.words)||d.words.length<4)throw new Error('invalid data');state.words=d.words;state.wordMap=new Map(state.words.map(w=>[normalize(w.word),w]));populatePosFilter();els.loading.hidden=true;els.content.hidden=false;renderQuestion();routeFromHash()}catch(e){console.error(e);els.loading.hidden=true;els.error.hidden=false;els.error.textContent='بارگذاری واژه‌ها انجام نشد.'}}
els.next.addEventListener('click',renderQuestion);els.feedbackBackdrop.addEventListener('click',renderQuestion);els.speak.addEventListener('click',()=>speak(state.current));els.typingForm.addEventListener('submit',answerTyped);els.keyboardBackspace.addEventListener('click',removeLastLetter);els.keyboardClear.addEventListener('click',clearTyped);els.modeButtons.forEach(b=>b.addEventListener('click',()=>{if(b.dataset.mode===state.mode)return;state.mode=b.dataset.mode;localStorage.setItem('fiQuizMode',state.mode);renderQuestion()}));els.hintButtons.forEach((b,i)=>b.addEventListener('click',()=>revealHint(i)));els.reset.addEventListener('click',()=>{state.correct=0;state.total=0;updateScore()});els.viewLinks.forEach(a=>a.addEventListener('click',e=>{e.preventDefault();state.detailWord=null;showView(a.dataset.viewLink)}));els.dictionarySearch.addEventListener('input',renderDictionaryList);els.dictionarySort.addEventListener('change',renderDictionaryList);els.dictionaryPosFilter.addEventListener('change',renderDictionaryList);els.dictionaryBack.addEventListener('click',()=>{state.detailWord=null;history.replaceState(null,'','#dictionary');renderDictionaryList()});els.detailSpeak.addEventListener('click',()=>speak(state.detailWord));els.practiceButtons.forEach(b=>b.addEventListener('click',()=>startFocusedPractice(b.dataset.practiceMode)));window.addEventListener('hashchange',routeFromHash);document.addEventListener('keydown',e=>{if(!state.answered&&[MODES.TRANSLATION,MODES.CLOZE_CHOICE].includes(state.mode)&&['1','2','3','4'].includes(e.key)){els.options.querySelectorAll('.option')[Number(e.key)-1]?.click()}});init();